version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: always
    
    
